# This file was generated by GoReleaser. DO NOT EDIT.
cask "growthbook" do
  version "2.4.0"

  on_macos do
    on_arm do
      sha256 "de142737c761ab6f79a33e066fc698c40dc5dd6f28464ef63f75fdb28d3d4eb9"
      url "https://github.com/growthbook/cli/releases/download/v#{version}/growthbook_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7e130a490f1c9e91a2f117b98c6bf2148381b2942e74c97f7f5e425447a5e763"
      url "https://github.com/growthbook/cli/releases/download/v#{version}/growthbook_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f5707ee9d430932fd7b1e84dc39bb4b014db3337c070fe327be9ae85363e138c"
      url "https://github.com/growthbook/cli/releases/download/v#{version}/growthbook_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6fc2714a32a7b9cec69fd1ebd27d98dffa184852d3fd6e0bfbe83c1b12e6d901"
      url "https://github.com/growthbook/cli/releases/download/v#{version}/growthbook_Linux_x86_64.tar.gz"
    end
  end

  name "growthbook"
  desc "Command-line interface for GrowthBook feature flags and experiments"
  homepage "https://docs.growthbook.io/tools/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "growthbook"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/growthbook"]
    end
  end

  # No zap stanza required
end
