# This file was generated by GoReleaser. DO NOT EDIT.
cask "growthbook" do
  version "2.1.1"

  on_macos do
    on_intel do
      sha256 "3ac1d018b949e47794ce5854a5ba3535decef885b1e86b4392d5201e2e3de0d5"
      url "https://github.com/growthbook/cli/releases/download/v#{version}/growthbook_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "10728b2589d7b5d997c6e7a49335f8fd5fb0a39f1ba3637db6d80aba26f46e87"
      url "https://github.com/growthbook/cli/releases/download/v#{version}/growthbook_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "34ddc4dd56a63a92d1cfa3664130196981b118dcf502254880f90bee0bf99a49"
      url "https://github.com/growthbook/cli/releases/download/v#{version}/growthbook_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0932da73738bdccb16ea489a59683d9f6989d60b3e5e377737dadc665cd3941a"
      url "https://github.com/growthbook/cli/releases/download/v#{version}/growthbook_Linux_arm64.tar.gz"
    end
  end

  name "growthbook"
  desc "Command-line interface for GrowthBook feature flags and experiments"
  homepage "https://docs.growthbook.io/tools/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "growthbook"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/growthbook"]
    end
  end

  # No zap stanza required

end
