# This file was generated by GoReleaser. DO NOT EDIT.
cask "growthbook" do
  version "2.0.1"

  on_macos do
    on_intel do
      sha256 "31be85f5642132822a37b255c4d5ea9cbecaeb9c74df9a492ecd512a62657acf"
      url "https://github.com/growthbook/cli/releases/download/v#{version}/growthbook_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8356d5f4cbe36945e8956beb1b8eda9f77e27862d21ae4d83c6697c2dc8a04f9"
      url "https://github.com/growthbook/cli/releases/download/v#{version}/growthbook_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "78d70fc39dd0f7ea5b63e981f650bda9ba08b60239825862adb8b3cb6de9a090"
      url "https://github.com/growthbook/cli/releases/download/v#{version}/growthbook_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "98117ac9c54956b93d0f8f5d0faed6ab8754fef92363c8033c40889b2cd06965"
      url "https://github.com/growthbook/cli/releases/download/v#{version}/growthbook_Linux_arm64.tar.gz"
    end
  end

  name "growthbook"
  desc "Command-line interface for GrowthBook feature flags and experiments"
  homepage "https://docs.growthbook.io/tools/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "growthbook"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/growthbook"]
    end
  end

  # No zap stanza required

end
